/**
 * Seed the question bank into D1 from `tiered qa cards.pdf`.
 *
 *   npm run import:pdf                # local D1 (what `npm run dev` uses)
 *   npm run import:pdf -- --remote    # the deployed database
 *   npm run import:pdf -- --sql-only  # just rewrite worker/seed-questions.sql
 *
 * Idempotent: rows are matched on the PDF card number, so re-running corrects the
 * seeded cards in place and leaves their accumulated statistics alone.
 */

import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { EXPECTED_CARDS, parsePdf, type ParsedCard } from './parse-cards.js'
import { TIER_NAMES, TIERS } from '../shared/src/types.js'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')

const args = process.argv.slice(2)
const remote = args.includes('--remote')
/** Regenerate worker/seed-questions.sql without touching any database. */
const sqlOnly = args.includes('--sql-only')
const pdfArg = args.find((a) => !a.startsWith('--'))
const pdfPath = pdfArg ? path.resolve(process.cwd(), pdfArg) : path.join(root, 'tiered qa cards.pdf')

const quote = (value: string | number | null) =>
  value === null ? 'NULL' : typeof value === 'number' ? String(value) : `'${value.replace(/'/g, "''")}'`

function toSql(cards: ParsedCard[]): string {
  // No BEGIN/COMMIT: D1 wraps a --file execution itself and rejects explicit
  // transaction statements.
  const lines = ['-- Generated by `npm run import:pdf`. Do not edit by hand.']
  for (const c of cards) {
    lines.push(
      'INSERT INTO questions (tier, difficulty, source_card, text, option_a, option_b, option_c,' +
        ' option_d, answer, explanation, active, created_at, updated_at) VALUES (' +
        [
          c.tier,
          quote(c.difficulty),
          c.sourceCard,
          quote(c.text),
          quote(c.options[0]),
          quote(c.options[1]),
          quote(c.options[2]),
          quote(c.options[3]),
          quote(c.answer),
          c.explanation ? quote(c.explanation) : 'NULL',
          1,
          "datetime('now')",
          "datetime('now')",
        ].join(', ') +
        ')' +
        // Matching on the card number is what keeps this idempotent; statistics
        // columns are deliberately left untouched, and so is `difficulty` — the PDF
        // has no opinion on it, so an admin's classification must survive a re-import.
        ' ON CONFLICT(source_card) DO UPDATE SET' +
        ' tier=excluded.tier, text=excluded.text, option_a=excluded.option_a,' +
        ' option_b=excluded.option_b, option_c=excluded.option_c, option_d=excluded.option_d,' +
        " answer=excluded.answer, updated_at=datetime('now');",
    )
  }
  return lines.join('\n') + '\n'
}

console.log(`Parsing ${pdfPath}`)
const { cards, problems } = parsePdf(pdfPath)
console.log(`  parsed ${cards.length}/${EXPECTED_CARDS} cards`)

const perTier = new Map<number, number>()
for (const c of cards) perTier.set(c.tier, (perTier.get(c.tier) ?? 0) + 1)
for (const tier of TIERS) {
  console.log(`  tier ${tier} ${TIER_NAMES[tier].padEnd(15)} ${perTier.get(tier) ?? 0}`)
}

if (problems.length > 0) {
  console.log(`\n${problems.length} problem(s) — these cards were NOT imported:`)
  for (const p of problems) console.log(`  - ${p}`)
}
if (cards.length === 0) {
  console.error('\nNothing to import.')
  process.exit(1)
}

const sqlPath = path.join(root, 'worker', 'seed-questions.sql')
fs.writeFileSync(sqlPath, toSql(cards))
console.log(`\nWrote ${path.relative(root, sqlPath)}`)

if (sqlOnly) {
  console.log('\n--sql-only: nothing was applied to a database.')
  process.exit(0)
}

const target = remote ? '--remote' : '--local'
console.log(`Applying schema and seed to ${remote ? 'the deployed' : 'the local'} database…`)
for (const file of ['schema.sql', 'seed-questions.sql']) {
  execFileSync(
    'npx',
    ['wrangler', 'd1', 'execute', 'medicine-ludo', target, `--file=${file}`, '--yes'],
    { cwd: path.join(root, 'worker'), stdio: 'inherit' },
  )
}
console.log('\nDone.')
